"""added user

Revision ID: 2ce39b3d2490
Revises: e240fa471b4f
Create Date: 2026-04-16 18:28:04.958982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2ce39b3d2490'
down_revision: Union[str, Sequence[str], None] = 'e240fa471b4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hash_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('participant', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'participant', 'user', ['user_id'], ['id'])
    op.add_column('team', sa.Column('created_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'team', 'user', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'team', type_='foreignkey')
    op.drop_column('team', 'created_by')
    op.drop_constraint(None, 'participant', type_='foreignkey')
    op.drop_column('participant', 'user_id')
    op.drop_table('user')
    # ### end Alembic commands ###